package task.lt.mybatis.dao;

import org.mybatis.cdi.Mapper;
import task.lt.mybatis.model.Bus;

import java.util.List;

@Mapper
public interface BusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    int deleteByPrimaryKey(Integer busId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    int insert(Bus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    Bus selectByPrimaryKey(Integer busId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    List<Bus> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    int updateByPrimaryKey(Bus record);
}