package task.lt.mybatis.dao;

import org.mybatis.cdi.Mapper;
import task.lt.mybatis.model.Driver;

import java.util.List;

@Mapper
public interface DriverMapper {
    List<Driver> selectAllWithTrips();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.driver
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    int deleteByPrimaryKey(Integer driverId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.driver
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    int insert(Driver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.driver
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    Driver selectByPrimaryKey(Integer driverId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.driver
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    List<Driver> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.driver
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    int updateByPrimaryKey(Driver record);
}