package task.lt.mybatis.dao;

import org.mybatis.cdi.Mapper;
import task.lt.mybatis.model.DriverBus;

import java.util.List;

@Mapper
public interface DriverBusMapper {
    void deleteByDriverId(Integer driverId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.driver_bus
     *
     * @mbg.generated Fri Apr 16 15:28:04 EEST 2021
     */
    int insert(DriverBus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.driver_bus
     *
     * @mbg.generated Fri Apr 16 15:28:04 EEST 2021
     */
    List<DriverBus> selectAll();
}