package task.lt.mybatis.dao;

import org.mybatis.cdi.Mapper;
import task.lt.mybatis.model.Ticket;

import java.util.List;

@Mapper
public interface TicketMapper {
    List<Ticket> selectAllWithTrip();
    //Trip selectTripNameById(@Param("tripId") Integer tripId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ticket
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ticket
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    int insert(Ticket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ticket
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    Ticket selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ticket
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    List<Ticket> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ticket
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    int updateByPrimaryKey(Ticket record);
}