package task.lt.mybatis.dao;

import org.mybatis.cdi.Mapper;

import task.lt.mybatis.model.TripLog;

import java.util.List;

@Mapper
public interface TripLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.trip_log
     *
     * @mbg.generated Sat Apr 10 20:36:41 EEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.trip_log
     *
     * @mbg.generated Sat Apr 10 20:36:41 EEST 2021
     */
    int insert(TripLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.trip_log
     *
     * @mbg.generated Sat Apr 10 20:36:41 EEST 2021
     */
    TripLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.trip_log
     *
     * @mbg.generated Sat Apr 10 20:36:41 EEST 2021
     */
    List<TripLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.trip_log
     *
     * @mbg.generated Sat Apr 10 20:36:41 EEST 2021
     */
    int updateByPrimaryKey(TripLog record);
}