package task.lt.mybatis.dao;

import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;
import task.lt.mybatis.model.Ticket;
import task.lt.mybatis.model.Trip;

import java.util.List;

@Mapper
public interface TripMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.trip
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.trip
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    int insert(Trip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.trip
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    Trip selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.trip
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    List<Trip> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.trip
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    int updateByPrimaryKey(Trip record);

    List<Trip> selectAllWithTickets();
    List<Ticket> selectTicketsByTripId(@Param("tripId") Integer tripId);
}