package task.lt.mybatis.model;

import java.util.List;

public class Bus {
    private List<Trip> trips;

    private List<Driver> drivers;

    public List<Trip> getTrips() {
        return trips;
    }

    public void setTrips(List<Trip> trips) {
        this.trips = trips;
    }

    public List<Driver> getDrivers() {
        return drivers;
    }

    public void setDrivers(List<Driver> drivers) {
        this.drivers = drivers;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.bus.bus_id
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    private Integer busId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.bus.current_fuel
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    private Integer currentFuel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.bus.plate_number
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    private String plateNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.bus.bus_id
     *
     * @return the value of public.bus.bus_id
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    public Integer getBusId() {
        return busId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.bus.bus_id
     *
     * @param busId the value for public.bus.bus_id
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    public void setBusId(Integer busId) {
        this.busId = busId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.bus.current_fuel
     *
     * @return the value of public.bus.current_fuel
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    public Integer getCurrentFuel() {
        return currentFuel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.bus.current_fuel
     *
     * @param currentFuel the value for public.bus.current_fuel
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    public void setCurrentFuel(Integer currentFuel) {
        this.currentFuel = currentFuel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.bus.plate_number
     *
     * @return the value of public.bus.plate_number
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    public String getPlateNumber() {
        return plateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.bus.plate_number
     *
     * @param plateNumber the value for public.bus.plate_number
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    public void setPlateNumber(String plateNumber) {
        this.plateNumber = plateNumber;
    }
}