package task.lt.mybatis.model;

public class DriverBus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.driver_bus.bus_id
     *
     * @mbg.generated Fri Apr 16 15:28:04 EEST 2021
     */
    private Integer busId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.driver_bus.driver_id
     *
     * @mbg.generated Fri Apr 16 15:28:04 EEST 2021
     */
    private Integer driverId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.driver_bus.bus_id
     *
     * @return the value of public.driver_bus.bus_id
     *
     * @mbg.generated Fri Apr 16 15:28:04 EEST 2021
     */
    public Integer getBusId() {
        return busId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.driver_bus.bus_id
     *
     * @param busId the value for public.driver_bus.bus_id
     *
     * @mbg.generated Fri Apr 16 15:28:04 EEST 2021
     */
    public void setBusId(Integer busId) {
        this.busId = busId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.driver_bus.driver_id
     *
     * @return the value of public.driver_bus.driver_id
     *
     * @mbg.generated Fri Apr 16 15:28:04 EEST 2021
     */
    public Integer getDriverId() {
        return driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.driver_bus.driver_id
     *
     * @param driverId the value for public.driver_bus.driver_id
     *
     * @mbg.generated Fri Apr 16 15:28:04 EEST 2021
     */
    public void setDriverId(Integer driverId) {
        this.driverId = driverId;
    }
}