package task.lt.mybatis.model;

public class Ticket {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ticket.id
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ticket.is_bought
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    private Boolean isBought;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ticket.price
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ticket.seat
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    private Integer seat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ticket.trip_id
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    private Integer tripId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ticket.id
     *
     * @return the value of public.ticket.id
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ticket.id
     *
     * @param id the value for public.ticket.id
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ticket.is_bought
     *
     * @return the value of public.ticket.is_bought
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    public Boolean getIsBought() {
        return isBought;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ticket.is_bought
     *
     * @param isBought the value for public.ticket.is_bought
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    public void setIsBought(Boolean isBought) {
        this.isBought = isBought;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ticket.price
     *
     * @return the value of public.ticket.price
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ticket.price
     *
     * @param price the value for public.ticket.price
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ticket.seat
     *
     * @return the value of public.ticket.seat
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    public Integer getSeat() {
        return seat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ticket.seat
     *
     * @param seat the value for public.ticket.seat
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    public void setSeat(Integer seat) {
        this.seat = seat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ticket.trip_id
     *
     * @return the value of public.ticket.trip_id
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    public Integer getTripId() {
        return tripId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ticket.trip_id
     *
     * @param tripId the value for public.ticket.trip_id
     *
     * @mbg.generated Sat Apr 10 20:15:58 EEST 2021
     */
    public void setTripId(Integer tripId) {
        this.tripId = tripId;
    }
}