package task.lt.mybatis.model;

import java.util.Date;

public class TripLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.trip_log.id
     *
     * @mbg.generated Sat Apr 10 20:36:41 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.trip_log.arrival_time
     *
     * @mbg.generated Sat Apr 10 20:36:41 EEST 2021
     */
    private String arrivalTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.trip_log.bus_id
     *
     * @mbg.generated Sat Apr 10 20:36:41 EEST 2021
     */
    private Integer busId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.trip_log.creation_date
     *
     * @mbg.generated Sat Apr 10 20:36:41 EEST 2021
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.trip_log.departure_time
     *
     * @mbg.generated Sat Apr 10 20:36:41 EEST 2021
     */
    private String departureTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.trip_log.driver_id
     *
     * @mbg.generated Sat Apr 10 20:36:41 EEST 2021
     */
    private Integer driverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.trip_log.name
     *
     * @mbg.generated Sat Apr 10 20:36:41 EEST 2021
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.trip_log.id
     *
     * @return the value of public.trip_log.id
     *
     * @mbg.generated Sat Apr 10 20:36:41 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.trip_log.id
     *
     * @param id the value for public.trip_log.id
     *
     * @mbg.generated Sat Apr 10 20:36:41 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.trip_log.arrival_time
     *
     * @return the value of public.trip_log.arrival_time
     *
     * @mbg.generated Sat Apr 10 20:36:41 EEST 2021
     */
    public String getArrivalTime() {
        return arrivalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.trip_log.arrival_time
     *
     * @param arrivalTime the value for public.trip_log.arrival_time
     *
     * @mbg.generated Sat Apr 10 20:36:41 EEST 2021
     */
    public void setArrivalTime(String arrivalTime) {
        this.arrivalTime = arrivalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.trip_log.bus_id
     *
     * @return the value of public.trip_log.bus_id
     *
     * @mbg.generated Sat Apr 10 20:36:41 EEST 2021
     */
    public Integer getBusId() {
        return busId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.trip_log.bus_id
     *
     * @param busId the value for public.trip_log.bus_id
     *
     * @mbg.generated Sat Apr 10 20:36:41 EEST 2021
     */
    public void setBusId(Integer busId) {
        this.busId = busId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.trip_log.creation_date
     *
     * @return the value of public.trip_log.creation_date
     *
     * @mbg.generated Sat Apr 10 20:36:41 EEST 2021
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.trip_log.creation_date
     *
     * @param creationDate the value for public.trip_log.creation_date
     *
     * @mbg.generated Sat Apr 10 20:36:41 EEST 2021
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.trip_log.departure_time
     *
     * @return the value of public.trip_log.departure_time
     *
     * @mbg.generated Sat Apr 10 20:36:41 EEST 2021
     */
    public String getDepartureTime() {
        return departureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.trip_log.departure_time
     *
     * @param departureTime the value for public.trip_log.departure_time
     *
     * @mbg.generated Sat Apr 10 20:36:41 EEST 2021
     */
    public void setDepartureTime(String departureTime) {
        this.departureTime = departureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.trip_log.driver_id
     *
     * @return the value of public.trip_log.driver_id
     *
     * @mbg.generated Sat Apr 10 20:36:41 EEST 2021
     */
    public Integer getDriverId() {
        return driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.trip_log.driver_id
     *
     * @param driverId the value for public.trip_log.driver_id
     *
     * @mbg.generated Sat Apr 10 20:36:41 EEST 2021
     */
    public void setDriverId(Integer driverId) {
        this.driverId = driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.trip_log.name
     *
     * @return the value of public.trip_log.name
     *
     * @mbg.generated Sat Apr 10 20:36:41 EEST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.trip_log.name
     *
     * @param name the value for public.trip_log.name
     *
     * @mbg.generated Sat Apr 10 20:36:41 EEST 2021
     */
    public void setName(String name) {
        this.name = name;
    }
}